### ISSUE TITLE
Linux throws 'System.DllNotFoundException'

### ISSUE THREAD

**Issue by vilyo** [arklumpus/MuPDFCore#1]
Hello, I am learning the knowledge of PDF. 
I found that your project is great. I followed your instructions and successfully ran PDFViewerDemo on both Windows and Mac. 
But under Linux, I got this error. I don’t know where the file "MuPDFWrapper" is. Is it the directory "\native\out\build\linux-x64\MuPDFWrapper"? I have this directory but still have this abnormal. There is also libMuPDFWrapper.so in my running directory.

![图片](https://user-images.githubusercontent.com/24307150/101445845-304c9880-395d-11eb-8bed-bc7a680c7f9d.png)

**Comment by vilyo** [comment]
My Linux OS is Debian 9

**Comment by vilyo** [comment]
I recompiled libMuPDFWrapper.so for Linux, copied it to my program running directory, and now it runs perfectly. It should be a problem with libMuPDFWrapper.so that I compiled before.

**Comment by arklumpus** [comment]
Hi, glad you like it and you managed to get it working! If you are interested in the inner workings of PDF, you might want to have a look at [VectSharp.PDF](https://github.com/arklumpus/VectSharp/) - the library produces PDF files from scratch and therefore contains code to deal with the complexities of the format. There is also an option to leave all streams in the file uncompressed, so that you can have a look and prod around the file with a text editor.

**Comment by vilyo** [comment]
Your project is great, thank you for your suggestion, I'm learning about VectSharp now.
