### ISSUE TITLE
Don't work with musl-based linux distros

### ISSUE THREAD

**Issue by ju5tas** [arklumpus/MuPDFCore#22]
Hi!

I am trying to use MuPDFCore in container with Alpina Linux, but it doesn't work.
Here ldd result:
```
/app/runtimes/linux-x64/native # ldd libMuPDFWrapper.so
        /lib/ld-musl-x86_64.so.1 (0x7fafacb69000)
        libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x7fafa9cdf000)
        libm.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fafacb69000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fafa9cc1000)
        libc.so.6 => /lib/ld-musl-x86_64.so.1 (0x7fafacb69000)
Error relocating libMuPDFWrapper.so: __isnan: symbol not found
Error relocating libMuPDFWrapper.so: __isinff: symbol not found
Error relocating libMuPDFWrapper.so: __finite: symbol not found
Error relocating libMuPDFWrapper.so: __isnanf: symbol not found
Error relocating libMuPDFWrapper.so: __isinf: symbol not found
```

Can you add linux-musl-x64 support?

**Comment by arklumpus** [comment]
Hi, version 1.7.0 now has support for both linux-musl-x64 and linux-musl-arm64!

**Comment by ju5tas** [comment]
Thanks!
But nuget latest version is still 1.6.0

**Comment by arklumpus** [comment]
Yeah, unfortunately the upload failed because adding the new assets caused the NuGet package to become too big...

I removed the musl native library from the NuGet to get it below the limit, and I have attached it to the release here on GitHub (https://github.com/arklumpus/MuPDFCore/releases/tag/v1.7.0). Basically, you will have to download the native asset manually and put it in the same folder as the executable, replacing the default `libMuPDFWrapper.so` created when you build your program (which is the normal glibc-based one).
