### ISSUE TITLE
Why does the rendered page not display the signature stamp

### ISSUE THREAD

**Issue by vilyo** [arklumpus/MuPDFCore#3]
I opened a PDF with a signature, but found that your project does not display the stamp. Is there any way to display it?

![图片](https://user-images.githubusercontent.com/24307150/103081566-27bdb880-4613-11eb-97df-e5cb0bfada9b.png)
Opend by PDFViewerDemo

![图片](https://user-images.githubusercontent.com/24307150/103081602-41f79680-4613-11eb-9104-d75c84f6c359.png)
Opend by SumatraPDF

**Comment by arklumpus** [comment]
That has probably something to do with annotations not being rendered. Could you please attach an example file showing the problem?

**Comment by vilyo** [comment]
OK, I tried every PDF with a signature stamp and it can’t be displayed. For example, this PDF has a signature stamp on it.
[test.pdf](https://github.com/arklumpus/MuPDFCore/files/5739770/test.pdf)

**Comment by arklumpus** [comment]
OK thank you, I just needed a file to test the fix. The problem was that the function returning the display list would only return the page contents, and not the annotations (signature stamps are a kind of annotation). This should be fixed in v1.1.0; I have added an optional `bool includeAnnotations` parameter that controls whether annotations are included in the page (which is the new default) or not.
