### ISSUE TITLE
MuPDFCore.MuPDFRenderer : Incomplete Clearing of Selection Effect

### ISSUE THREAD

**Issue by envy666** [arklumpus/MuPDFCore#32]
When selecting text on a PDF, a background effect is drawn over the selected text. However, upon switching pages or opening another PDF, the previous selection effect isn't cleared.

I attempted to address this by adding this.Selection = null within the Initialize method after reviewing the source code. Unfortunately, this modification didn't produce the desired outcome.

Thank you once again for your efforts in providing us with such a valuable tool.

**Comment by arklumpus** [comment]
Hi, thanks for noticing this! I have just released MuPDFCore.MuPDFRenderer v1.9.1, where this is fixed.

The issue was that the selection was set to `null` after the page had already been disposed, therefore the selection quads were not updated.

I'm closing this, feel free to reopen if you still have the problem (or open a new issue if you have other questions)!
