### ISSUE TITLE
What is the best way to get the text of a pdf?

### ISSUE THREAD

**Issue by joslat** [arklumpus/MuPDFCore#7]
Hi, 
First, thanks for the effort put in this library, greatly appreciate it!  👍  :)
I more or less got it done but I am unsure I am doing it fully correctly or having the full picture.
At the moment I do not see a document.GetText  as can be found in pymupdf lib, https://pymupdf.readthedocs.io/en/latest/app2.html#plain-text so what I did is:
iterate on all pages of a document to get the MuPdfStructuredTextPage(s).
From each, get the MuPDFStructuredTextBlocks
From each get the MuPdftext lines
and concatenate those in a big string if they are not null or empty/whitespace...
Is this correct? meaning the best way to do this... or is there a better way?

I assume this will provide a UTF-8  Unicode... right?
What happens with text that comes in other languages? will we get it with that encoding or should we do a conversion?

Also to do this properly, we should use the OCR functions over all images, to try to obtain the text from them... right?

**Comment by arklumpus** [comment]
Hi!

Yes, I think your approach makes sense, and it should produce results that are equivalent to the `extractText` function of the Python library. I will see if I can implement a method to do that on the `MuPDFStructuredTextPage` class, but my approach would be exactly like what you describe. Note that, as is the case for the Python library, the order in which the text elements are returned may or may not be the same as the reading order of the document (see #2 for more discussion about this).

The native MuPDF library returns characters as Unicode code points. When MuPDFCore interacts with the library to create a `MuPDFStructuredTextCharacter` object, it stores the Unicode code point in the `CodePoint` property of the `MuPDFStructuredTextCharacter` and, at the same time, converts it to a `string` using the [`Char.ConvertFromUtf32`](https://docs.microsoft.com/en-us/dotnet/api/system.char.convertfromutf32?view=net-5.0) method (note that C# strings are UTF-16). _In theory_ I expect that this should work regardless of the language (although I have not been able to test it with anything using a non-Western locale); in any case, the original Unicode character returned by MuPDF is still there, so if you need to convert to a `string` it using a different method it should not be an issue.

Finally, MuPDF 1.18 uses [Tesseract](https://github.com/tesseract-ocr/tesseract) to do OCR. MuPDFCore currently embeds MuPDF 1.17 instead (which has no OCR functions); in the [MuPDF website](https://mupdf.com/docs/api/changes.html) they do not list any API changes between the two versions, though I am not sure whether this is because there _are_ no incompatible changes, or just because they have not update the documentation. Assuming I can update the library to use MuPDF 1.18, providing hooks for the OCR function should not be too hard. An alternative would be to directly use a .NET wrapper for the OCR library like [this](https://github.com/charlesw/tesseract), but it seems inefficient, considering that MuPDF already comes with the library.

In both cases, you would also need to download the language files from [tessdata_best](https://github.com/tesseract-ocr/tessdata_best) or [tessdata_fast](https://github.com/tesseract-ocr/tessdata_fast). I wonder what would be the best approach for this: I have seen multiple libraries leaving this responsibility to the developer or even to the end user; an alternative would be to embed all the language files in a NuGet package that would take care of copying them to the build folder.

**Comment by joslat** [comment]
Cool! 
Really quick responses and accurate too, the least ;)
As mine is already working, I'd be glad to fork and do a PR... :)

**Comment by arklumpus** [comment]
Ok, this is now implemented in v1.2.8, thank you again for the suggestion and pull request!

I am leaving this open while I investigate using MuPDF 1.18 and the OCR stuff.

**Comment by arklumpus** [comment]
As expected, compiling MuPDF 1.18 was a nightmare, but I think I made it! 😁

Version 1.3.1 has the updated MuPDF and the OCR functions; there are new overloads of the `GetStructuredTextPage` and `ExtractText` methods that accept a `TesseractLanguage` parameter and do the OCR (see the [Readme](https://github.com/arklumpus/MuPDFCore#optical-character-recognition-ocr-using-tesseract) or the docs for more information).

I am closing this for now, but any feedback is welcome! Feel free to just add a comment here, reopen this or create a new issue if something is not clear / does not work!
