### ISSUE TITLE
Always get MuPDFCore.MuPDFException:“Cannot open document” exception in PDFViewer demo

### ISSUE THREAD

**Issue by esonhon** [arklumpus/MuPDFCore#9]
Windows 10 x64 with vs2019, use the original source, when open a pdf or xps file, it fires MuPDFCore.MuPDFException:“Cannot open document” exception. Then I upgrade the related AVA and Mupdf package to the newest version, exception still there.

**Comment by arklumpus** [comment]
Hi! That sounds strange...

1. When you start the application, do you see the introductory image telling you how to pan and zoom around the document? Or does it crash before even opening?

2. Does this happen with any PDF/XPS document, or just with a particular file you are trying to open? Would you be able to upload/send me a "problematic" file? [Here](https://github.com/arklumpus/MuPDFCore/files/6983913/Document1.pdf) is a file that should definitely work, can you open this?

3. Does it matter where the file is located? E.g. try putting the PDF file in the Desktop, can you open it then?

4. What happens if you try to render a document using the library? E.g., create a new console app project, add the MuPDFCore NuGet package, and try this code:
    ```CSharp
    using MuPDFCore;
    // ...
    static void Main(string[] args)
    {
        using MuPDFContext ctx = new MuPDFContext();
        using MuPDFDocument doc = new MuPDFDocument(ctx, "path/to/your/file.pdf");
        doc.SaveImage(0, 1, PixelFormats.RGBA, "test.png", RasterOutputFileTypes.PNG);
    }
    ```
    This should render the first page of your document to an image file called `test.png` in the same folder as the executable (e.g. the bin/Debug folder of your project). Does this work, or does it give you the same error? Do you see any useful messages in the console?

**Comment by esonhon** [comment]
Thanks.
1. Yes, the introduction image showing.
2. 3.Tried 10+ pdf files and 3 more xps files, only Document1.pdf in source code directory can opened. Copied this file to directory of other pdf files, only this one could be opened.
4. Will try it ASAP.

**Comment by arklumpus** [comment]
It seems that there is _something_ about the files you have been trying to open that crashes MuPDF... Can you send me a test file? 

Another thing you could try would be to open the files using SumatraPDF (https://www.sumatrapdfreader.org/free-pdf-reader), which also uses MuPDF internally... If they don't work there either, it's likely to be a bug within MuPDF itself.

**Comment by esonhon** [comment]
Thanks for ur kindly help.
"What happens if you try to render a document using the library? E.g., create a new console app project, add the MuPDFCore NuGet package, and try this code:"
It works, I got the png image right there. Eh... It's really strange.

**Comment by arklumpus** [comment]
Indeed... I definitely need a file to reproduce this though, otherwise I have no idea how to investigate 😅 Would you be able to send me one?

**Comment by esonhon** [comment]
After trying and trying, I found the actual problem.
In my scenerio, the OCR function causes the exception, I create a new project without any OCR function initialization, or just modify the demo, delete OCR related codes, it works!
Thanks for your great works!
